# Base URL do ViaCEP (configKey = "via-cep")
quarkus.rest-client.via-cep.url=https://viacep.com.br
quarkus.rest-client.via-cep.connect-timeout=3000
quarkus.rest-client.via-cep.read-timeout=5000

# H2 em memória (DEV)
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:clientes;DB_CLOSE_DELAY=-1
quarkus.datasource.username=sa
quarkus.datasource.password=sa

# Hibernate ORM - criar tabelas automaticamente
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true