# Datasource (exemplo H2)
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:emprestimos;DB_CLOSE_DELAY=-1
quarkus.datasource.username=sa
quarkus.datasource.password=sa
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

# Base URL do ViaCEP (configKey = "via-cep")
quarkus.rest-client.via-cep.url=https://viacep.com.br
quarkus.rest-client.via-cep.connect-timeout=3000
quarkus.rest-client.via-cep.read-timeout=5000

# REST Client (API externa)
quarkus.rest-client.taxas-api.url=http://localhost:9000

# Security (Basic Auth via properties)
quarkus.security.users.file.enabled=true
quarkus.security.users.file.users=users.properties
quarkus.security.users.file.roles=roles.properties
quarkus.security.users.file.plain-text=true
